name: Sync

on:
  workflow_dispatch:
    inputs:
      github-org:
        description: 'Your Github org name or Github username associated with your repo'
        required: true
      github-repo:
        description: 'Your Github repo name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add to Notion
        uses: ./
        with:
          github-org: ${{ github.event.inputs.github-org }}
          github-repo: ${{ github.event.inputs.github-repo }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: ${{ secrets.NOTION_DATABASE }}
          

    
