name: Sync

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add GitHub Issues to Notion
        uses: ./
        with:
          github-org: ${{ github.event.inputs.github-org }}
          github-repo: ${{ github.event.inputs.github-repo }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: ${{ secrets.NOTION_DATABASE }}
